## Part 1: Tensors Operations
It turns out neural network computations are just a bunch of linear algebra operations on tensors, a generalization of matrices. A vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor, an array with three indices is a 3-dimensional tensor (RGB color images for example). The fundamental data structure for neural networks are tensors and PyTorch (as well as pretty much every other deep learning framework) is built around tensors.

This notebook we will go through some basic PyTorch tensors operations: 
* [Tensors Operations](#tensors_operations)
* [Reshaping](#reshaping)
* [Numpy to Torch and Torch to Numpy](#numpytotorch)


In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
from torch import nn
from torch import optim
import torch.nn.functional as F

from torchvision import datasets, transforms, models

import helper

First, let's see how we work with PyTorch tensors. These are the fundamental data structures of neural networks and PyTorch, so it's imporatant to understand how these work.

<a id='tensors_operations'></a>
## Tensors Operations

In [2]:
# create a random 3 by 2 tensor (tensor is matric)
x = torch.rand(3,2)
x

tensor([[ 0.2036,  0.5635],
        [ 0.7142,  0.8242],
        [ 0.0737,  0.8818]])

In [3]:
# create a 3 by 3 ones matric
y = torch.ones(3,2)
y

tensor([[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]])

In [4]:
# add
z = x+y
z

tensor([[ 1.2036,  1.5635],
        [ 1.7142,  1.8242],
        [ 1.0737,  1.8818]])

In general PyTorch tensors behave similar to Numpy arrays. They are zero indexed and support slicing.

In [5]:
# get first row
print("first row values are: ", z[0])

# get first column
print("first column values are: \n", z[:,0:1])

# get first element
print("first element in the matric is ", z[0][0])

first row values are:  tensor([ 1.2036,  1.5635])
first column values are: 
 tensor([[ 1.2036],
        [ 1.7142],
        [ 1.0737]])
first element in the matric is  tensor(1.2036)


Tensors typically have two forms of methods, one method that returns another tensor and another method that performs the operation in place. That is, the values in memory for that tensor are changed without creating a new tensor. In-place functions are always followed by an underscore, for example z.add() and z.add_().

In [6]:
# retruns another tensor: add 1 to each element
z.add(1)

tensor([[ 2.2036,  2.5635],
        [ 2.7142,  2.8242],
        [ 2.0737,  2.8818]])

In [7]:
# but z is not change, since the above change is not in place
z

tensor([[ 1.2036,  1.5635],
        [ 1.7142,  1.8242],
        [ 1.0737,  1.8818]])

In [8]:
# Add 1 and update z tensor in-place
z.add_(1)

tensor([[ 2.2036,  2.5635],
        [ 2.7142,  2.8242],
        [ 2.0737,  2.8818]])

In [9]:
# z is changed
z

tensor([[ 2.2036,  2.5635],
        [ 2.7142,  2.8242],
        [ 2.0737,  2.8818]])

<a id='reshaping'></a>
## Reshaping
Reshaping tensors is a really common operation. First to get the size and shape of a tensor use .size(). Then, to reshape a tensor, use .resize_(). Notice the underscore, reshaping is an in-place operation.

In [10]:
# check the size of z, currently is 3 by 2, that's 3 rows 2 columns
z.size()

torch.Size([3, 2])

In [11]:
# reshape it to 2 by 3
z.resize_(2,3)

tensor([[ 2.2036,  2.5635,  2.7142],
        [ 2.8242,  2.0737,  2.8818]])

In [12]:
z

tensor([[ 2.2036,  2.5635,  2.7142],
        [ 2.8242,  2.0737,  2.8818]])

<a id = 'numpytotorch'></a>
## Numpy to Torch and back
Converting between Numpy arrays and Torch tensors is super simple and useful. To create a tensor from a Numpy array, use torch.from_numpy(). To convert a tensor to a Numpy array, use the .numpy() method.

In [13]:
# define a numpy array, 4 by 3 matrix
a = np.random.rand(4, 3)
a

array([[0.79793041, 0.53976973, 0.20547582],
       [0.164102  , 0.98931873, 0.59673385],
       [0.33789702, 0.27307065, 0.85549233],
       [0.47132206, 0.44175656, 0.43057141]])

In [14]:
# convert numpy array to tensor
b = torch.from_numpy(a)
b

tensor([[ 0.7979,  0.5398,  0.2055],
        [ 0.1641,  0.9893,  0.5967],
        [ 0.3379,  0.2731,  0.8555],
        [ 0.4713,  0.4418,  0.4306]], dtype=torch.float64)

In [15]:
# convert tensor back to numpy array
b.numpy()

array([[0.79793041, 0.53976973, 0.20547582],
       [0.164102  , 0.98931873, 0.59673385],
       [0.33789702, 0.27307065, 0.85549233],
       [0.47132206, 0.44175656, 0.43057141]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [16]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[ 1.5959,  1.0795,  0.4110],
        [ 0.3282,  1.9786,  1.1935],
        [ 0.6758,  0.5461,  1.7110],
        [ 0.9426,  0.8835,  0.8611]], dtype=torch.float64)

In [17]:
# check b is changed
b

tensor([[ 1.5959,  1.0795,  0.4110],
        [ 0.3282,  1.9786,  1.1935],
        [ 0.6758,  0.5461,  1.7110],
        [ 0.9426,  0.8835,  0.8611]], dtype=torch.float64)

In [18]:
# check if a is also updated - YES
a

array([[1.59586082, 1.07953946, 0.41095164],
       [0.328204  , 1.97863746, 1.19346769],
       [0.67579404, 0.54614131, 1.71098467],
       [0.94264412, 0.88351312, 0.86114282]])